config/routes.rb
Rails.application.routes.draw do
  get '/actor/:full_name' => 'cast_members#show_by_name', as: 'name'
  root 'movies#principal'
  

  resources :movies do
    collection do
      get :random_movies
      get :search
      get :search_category
    end

    member do
      patch :reduce_counter
      patch :increment_counter
    end

    resources :reviews
  end

  resources :movies do
    resources :cast_members
  end

  resources :cast_members do
    resources :movies
  end

  resources :movies do
    resources :categories
  end

  resources :categories do
    resources :movies
  end

  resources :music do
    collection do
      get :random_songs
      get :search_song
      get :search_category
    end
  end

  resources :song do
    resources :artist
  end

  resources :artist do
    resources :songs
  end

  resources :artist do
    resources :tags
  end

  resources :tags do
    resources :artist
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :songs
	belongs_to :artist

	validates :title, uniqueness: {message: "Error, there is an album with this title"}
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :songs
	has_many :albums
	has_and_belongs_to_many :tags

	validates :info, presence: {message: "Error, there isn´t any info"}
	validates :name, presence: {message: "Error, there isn´t any name"}
	validates :name, uniqueness: {message: "Error, there is an artist with this name"}
	paginates_per 20
end

app/models/cast_member.rb
class CastMember < ActiveRecord::Base
	has_and_belongs_to_many :movies
	validates :full_name, presence: {message: "Error, there isn't any name"}
	validates :full_name, uniqueness: {message: "Error, there is an actor with this name"}
	paginates_per 20
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :movies
	validates :name, presence: {message: "Error, there isn´t any name"}
	validates :name, uniqueness: {message: "Error, there is a category with this title"}
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_and_belongs_to_many :cast_members
	has_many :reviews
	has_and_belongs_to_many :categories

	validates :year, presence: {message: "Error, there isn't any year"}
	validates :plot, presence: {message: "Error, there isn't any plot"}
	validates :poster, presence: {message: "Error, there isn't any poster"}
	validates :trailer_url, presence: {message: "Error, there isn't any trailer url"}
	validates :title, uniqueness: {message: "Error, there is a movie with this title"}

	scope :search, ->(title) {
		where(["lower(title) LIKE (?)","%#{title.downcase}%"])
	}

	def self.last_created_movies(n)
		movie = order(created_at: :desc).limit(n)
		unless movie.present?
			raise
	ActiveRecord::RecordNotFound.new("couldn´t find movie with id=#{id}")
	end
	movie
	end

	paginates_per 12
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :movie
	validates :reviewer, presence: {message: "Error, there isn't any reviewer"}
	validates :content, presence: {message: "Error, there isn't any content"}
end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :artist
	belongs_to :album
	validates :title, uniqueness: {message: "Error, there is a song with this title"}
	validates :title, presence: {message: "Error, there isn´t any title"}
	validates :listeners, presence: {message: "Error, there isn´t any listeners"}
	validates :video_url, presence: {message: "Error, there isn´t any video_url"}
	paginates_per 12
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :artists
	validates :name, presence: {message: "Error, there isn´t any name"}
end

app/models/tag_and_artist.rb
class TagAndArtist < ActiveRecord::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :set_movie, only: [:edit, :update, :destroy, :increment_counter, :reduce_counter]

	def index
		@movies = Movie.all.order(counter: :asc).order(year: :desc).page params[:page]
	end

	def show
		@movie = Movie.find_by(id: params[:id])

		unless @movie.present?
			@movies = Movie.last_created_movies(10)

	  		render 'error', layout: 'errorlayout'
		end
	end

	def principal
		@movies = Movie.last_created_movies(10)
	end

	def edit
		
	end

	def update
		if @movie.update_attributes movie_params
			redirect_to action: 'index', controller: 'movies', movie_id: @movie.id
			#redirect_to @movie
			#redirect_to movies_path
		else
			render 'edit'
		end
	end

	def destroy
		@movie.destroy
		redirect_to action: 'index', controller: 'movies', movie_id: @movie.id
	end

	def reduce_counter
		@movie.update(counter: @movie.counter - 1)

		redirect_to movies_path
	end

	def increment_counter
		@movie.update(counter: @movie.counter + 1)

		redirect_to movies_path
	end

	def search
		@movies = Movie.search(params[:title]).page params[:page]

		if @movies != []
			@movies
		else
		 	search = Imdb::Search.new params[:title]
		 	@imdb = search.movies[0..10]

		 	@movies = @imdb.inject(Array.new) do |all_movies, imdb|
		 		movie = Movie.find_or_create_by(title: imdb.title, plot: imdb.plot, poster: imdb.poster, year: imdb.year, trailer_url: imdb.trailer_url)
		 		imdb.genres.each do |genre|
		 			category = Category.find_or_create_by name: genre
		 			movie.categories << category
		 		end

		 		 imdb.cast_members.each do |imdb_member|	
		 		 	my_member = CastMember.find_or_create_by full_name: imdb_member
	  		 		movie.cast_members << my_member
		 		 end
		 		all_movies << movie if movie.save
		 		all_movies
		 	end
		 	@movies
		end
	end

	def search_category
		@categories = Category.where(name: params[:category]).page(params[:page])
	end

 	def random_movies
 		@movie = Movie.find_by_id(rand(Movie.count))
 	end

 	def principal
 		
 	end

 	private
 	def set_movie
 		@movie = Movie.find params[:id]
 	end

 	def movie_params
		params.require(:movie).permit(:title, :plot, :poster, :year)
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	class ProjectsController < ApplicationController
	def index
		@projects = Project.last_created_projects(10)
	end

	def show
		@project = Project.find params[:id]
		rescue
			@projects = Project.last_created_projects(10)
	  		render 'error', layout: 'errorlayout'
	end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/cast_member_helper.rb
module CastMemberHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/movies/_form.html.erb
<h1>FORM</h1>
<p>Movie ID:<%= @movie.id %></p>

<% if @movie.errors.any? %>
	<ul>
		<% @movie.errors.full_messages.each do |error_msg| %>
			<li><%= error_msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for [@movie] do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title%>
	<br>
	<%= f.label :plot %>
	<%= f.text_field :plot%>
	<br>
	<%= f.label :poster %>
	<%= f.text_field :poster %>
	<br>
	<%= f.label :year %>
	<%= f.number_field :year %>
	<br>

	<%= f.submit 'Save' %>
<% end %>

app/views/movies/edit.html.erb
<%= render 'form' %>

app/views/movies/index.html.erb
<section class="movies_header">

<h1>Movies</h1>

<div class="moverboton">
<a href="/movies/random_movies?" class="rotate">
	<span></span>
    <span></span>
    <span>Random<br><br>movie!</span>
</a>
</div>

<%= form_tag(search_movies_path, method: :get) do %>
<%= text_field_tag'title',nil, placeholder: 'Search movie by title...' %>
<%= submit_tag'Search', class: 'submit_search' %>
<% end %>

<dl class="accordion" data-accordion="">
  <dd class="accordion-navigation">
    <a href="#panel1">Search by category &#8616;</a>
    <div id="panel1" class="content">
        <dl class="tabs" data-tab="">
	      	<div class="category_form">
				<form accept-charset="UTF-8" action="/movies/search_category" method="get"><div style="display:none"><input name="utf8" type="hidden" value="✓"></div>
					<div>
						<%  Category.all.each do |category| %>
				   			<div class="each_category"> <%= check_box_tag 'category[]', category.name %> <%= category.name %> </div>
						<% end %>
					</div>

					<div class="submit_category_search">
						<input name="commit" type="submit" value="Search">
					</div>
				</form>
			</div>
	  	</dl>
	  	</div>
	</dd>
</dl>

</section>


<section class='movie_list'>
	<% if @movies == [] %>
		There isn´t any movies in data base
	<%else%>
		<ul><% @movies.each do |movie| %>
			<div class='movie_preview'>
			<% if movie == nil %>
				There isn´t any movie
			<% else %>
				<li>
					<h4><%= link_to(movie.title, movie_path(movie.id)) %></h4> <br> ID: <%= movie.id %> -View: <%= movie.counter %>
					<p><%= link_to("View +1", increment_counter_movie_path(movie), method: :patch) %></p>
					<p><%= link_to("View -1", reduce_counter_movie_path(movie), method: :patch) %></p>
					<br><%= link_to(image_tag(movie.poster, alt: movie.poster), movie_path(movie)) %></br>

				</li>

				<p><%= link_to("Edit", edit_movie_path(movie)) %></p>
				<p><%= link_to("Delete",  movie_path(movie), method: :delete, data:{confirm: "Are you sure?"}) %></p>
			<% end %>	
			</div>
		<%end%></ul>
	<% end %>
</section>

<div class='pagination_section'><p><%= paginate @movies %></p></div>

<script src="assets/jquery.js"></script>
<script src="assets/foundation.js"></script>
<script src="assets/foundation.accordion.js"></script>

<script>
  $(document).foundation({
    accordion: {
      callback : function (accordion) {
        console.log(accordion);
      }
    }
  });
</script>

app/views/movies/principal.html.erb
<style>
@font-face {
    font-family: "Principal";
    src: url(assets/principal.ttf) format("truetype");
}

body {
	background-color: black;
}
article {
	background-image: url(assets/cascos.jpg);
	background-size: 1300px 800px;
}

#text {
position: absolute;
width: 1000px;
height: 200px;
left: 35%;
top: 35%;
margin-left: -300px;
margin-top: -60px;
text-align: center;
text-transform: uppercase;
-webkit-tranform: translateZ(0);
-webkit-transition-duration: 0.05s;
-moz-tranform: translateZ(0);
text-shadow:0px 0px 0 rgba(0, 43, 121, 1),0px -1px 0 rgba(0, 43, 121, 1),0px -2px 0 rgb(-30,-21,225),0px -3px 0 rgbrgba(0, 43, 121, 1),0px -4px 0 rgb(-43,-34,212),0px -5px 0 rgb(-50,-41,205),0px -6px 0 rgb(-57,-48,198),0px -7px 0 rgb(-64,-55,191),0px -8px 0 rgbrgba(0, 43, 121, 1),0px -9px 0 rgb(-77,-68,178),0px -10px 0 rgb(-84,-75,171),0px -11px 0 rgb(-90,-81,165),0px -12px 0 rgb(-97,-88,158), 0px -13px 0 rgba(0, 43, 121, 1),0px -14px 13px rgba(0,0,0,0.6),0px -14px 1px rgba(0,0,0,0.5),0px 0px 13px rgba(0,0,0,.2);
}

#text h1, h2{
	color: rgba(0, 43, 121, 1);
	font-size: 110px;
	font-family: Principal;
}

</style>


<div id="text">
	<h1>What Can</h1>
	<h2>I DO?!</h2>
</div>

<script type="text/javascript">
var text = document.getElementById('text'),
	body = document.body,
	steps = 11;
function threedee (e) {
	var x = Math.round(steps / (window.innerWidth / 2) * (window.innerWidth / 2 - e.clientX)),
		y = Math.round(steps / (window.innerHeight / 2) * (window.innerHeight / 2 - e.clientY)),
		shadow = '',
		color1 = 0,
		color2 = 214,
		color3 = 220,
		radius = 5,
		i;
	
	for (i=0; i<steps; i++) {
		tx = Math.round(x / steps * i);
		ty = Math.round(y / steps * i);
		if (tx || ty) {
			color1 -= 3 * i;
			color2 -= 3 * i;
			color3 -= 3 * i;
			shadow += tx + 'px ' + ty + 'px 0 rgb(' + color1 + ', ' + color2 + ', ' + color3 + '), ';
		}
	}

	shadow += x + 'px ' + y + 'px 1px rgba(0,0,0,.2), ' + x*2 + 'px ' + y*2 + 'px 6px rgba(0,0,0,.3)';
	
	text.style.textShadow = shadow;
	text.style.webkitTransform = 'translateZ(0) rotateX(' + y*1.5 + 'deg) rotateY(' + -x*1.5 + 'deg)';
	text.style.MozTransform = 'translateZ(0) rotateX(' + y*1.5 + 'deg) rotateY(' + -x*1.5 + 'deg)';
}

document.addEventListener('mousemove', threedee, false);
</script>

app/views/movies/random_movies.html.erb
<div class= 'movie_show_items'>
	<h1><%= @movie.title%></h1>

	<ul>
		<li>Watch the trailer: <a href="<%= @movie.trailer_url%>" target="_blank">here</a></li>
		<br>
		<img src="<%= @movie.poster %>"/>
		<br>
		<li><%= @movie.year%></li>
		<br>
		<li><% @movie.categories[0..@movie.categories.length - 2].each do |category|%>
			<%= link_to(category.name,  category_path(category)) %>, 
		<%end%>
			<%= link_to(@movie.categories.last.name,  category_path(@movie.categories.last)) %>.
		</li>
		<br>
		<p id='synopsis'>Synopsis</p>
		<div id="plot"><li><%= @movie.plot%></li></div>
		<br>
		<p id='synopsis'>Cast members</p>
		<p><li><% @movie.cast_members[0..8].each do |a|%>
			<%= a.full_name %>, 
			<%end%>
		<%= @movie.cast_members.last.full_name %>.
		</li></p>
		<br>
		<p><li>Add your Review here: <%= link_to("Add review", new_movie_review_path(@movie)) %></li></p>
		<br>
		<p><li>See all the reviews here: <%= link_to("See reviews",  movie_reviews_path(@movie)) %></li></p>
	</ul>
</div>

app/views/movies/search.html.erb
<div class= 'movie_show_items'><h1>SEARCH</h1></div>

<% if @movies == [] %>
	Sorry, there isn´t any movie with this title.
<% else %>
	<ul><% @movies.each do |movie| %>
<div class= 'movie_show_items'>
	<h1><%=link_to(movie.title, movie_path(movie)) %></h1>

	<ul>
		<li>Watch the trailer: <a href="<%= movie.trailer_url%>" target="_blank">here</a></li>
		<br>
		<img src="<%= movie.poster %>"/>
		<br>
		<li><%= movie.year%></li>
		<br>
		<li><% movie.categories[0..movie.categories.length - 2].each do |category|%>
			<%= link_to(category.name,  category_path(category)) %>, 
		<%end%>
			<%= link_to(movie.categories.last.name,  category_path(movie.categories.last)) %>.
		</li>
		<br>
		<p id='synopsis'>Synopsis</p>
		<div id="plot"><li><%= movie.plot%></li></div>
		<br>
		<p id='synopsis'>Cast members</p>
		<p><li><% movie.cast_members[0..8].each do |a|%>
			<%= a.full_name %>, 
			<%end%>
		<%= movie.cast_members.last.full_name %>.
		</li></p>
		<br>
		<br>
	<% end %></ul>
</div>
<% end %>

app/views/movies/search_category.html.erb
<div class='song_show_items'>
	<ul>
		<% @categories.each do |category| %>
			<h1><%= category.name %></h1>
		<% end %>
		<% @categories.each do |category| %>
			<% category.movies.each do |movie| %>
				<li>
					<%= link_to(movie.title, movie_path(movie)) %>
				</li><br>
			<%end%>
		<% end %>
	</ul>
</div>

app/views/movies/show.html.erb
<div class= 'movie_show_items'>
	<h1><%= @movie.title%></h1>

	<ul>
		<li>Watch the trailer: <a href="<%= @movie.trailer_url%>" target="_blank">here</a></li>
		<br>
		<img src="<%= @movie.poster %>"/>
		<br>
		<li><%= @movie.year%></li>
		<br>
		<li><% @movie.categories[0..@movie.categories.length - 2].each do |category|%>
			<%= link_to(category.name,  category_path(category)) %>, 
		<%end%>
			<%= link_to(@movie.categories.last.name,  category_path(@movie.categories.last)) %>.
		</li>
		<br>
		<p id='synopsis'>Synopsis</p>
		<div id="plot"><li><%= @movie.plot%></li></div>
		<br>
		<p id='synopsis'>Cast members</p>
		<p><li><% @movie.cast_members[0..8].each do |a|%>
			<%= a.full_name %>, 
			<%end%>
		<%= @movie.cast_members.last.full_name %>.
		</li></p>
		<br>
		<p><li>Add your Review here: <%= link_to("Add review", new_movie_review_path(@movie)) %></li></p>
		<br>
		<p><li>See all the reviews here: <%= link_to("See reviews",  movie_reviews_path(@movie)) %></li></p>
	</ul>
</div>