config/routes.rb
Rails.application.routes.draw do
  get '/actor/:full_name' => 'cast_members#show_by_name', as: 'name'
  root 'movies#principal'
  

  resources :movies do
    collection do
      get :random_movies
      get :search
      get :search_category
    end

    member do
      patch :reduce_counter
      patch :increment_counter
    end

    resources :reviews
  end

  resources :movies do
    resources :cast_members
  end

  resources :cast_members do
    resources :movies
  end

  resources :movies do
    resources :categories
  end

  resources :categories do
    resources :movies
  end

  resources :music do
    collection do
      get :random_songs
      get :search_song
      get :search_category
    end
  end

  resources :song do
    resources :artist
  end

  resources :artist do
    resources :songs
  end

  resources :artist do
    resources :tags
  end

  resources :tags do
    resources :artist
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :songs
	belongs_to :artist

	validates :title, uniqueness: {message: "Error, there is an album with this title"}
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :songs
	has_many :albums
	has_and_belongs_to_many :tags

	validates :info, presence: {message: "Error, there isn´t any info"}
	validates :name, presence: {message: "Error, there isn´t any name"}
	validates :name, uniqueness: {message: "Error, there is an artist with this name"}
	paginates_per 20
end

app/models/cast_member.rb
class CastMember < ActiveRecord::Base
	has_and_belongs_to_many :movies
	validates :full_name, presence: {message: "Error, there isn't any name"}
	validates :full_name, uniqueness: {message: "Error, there is an actor with this name"}
	paginates_per 20
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :movies
	validates :name, presence: {message: "Error, there isn´t any name"}
	validates :name, uniqueness: {message: "Error, there is a category with this title"}
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_and_belongs_to_many :cast_members
	has_many :reviews
	has_and_belongs_to_many :categories

	validates :year, presence: {message: "Error, there isn't any year"}
	validates :plot, presence: {message: "Error, there isn't any plot"}
	validates :poster, presence: {message: "Error, there isn't any poster"}
	validates :trailer_url, presence: {message: "Error, there isn't any trailer url"}
	validates :title, uniqueness: {message: "Error, there is a movie with this title"}

	scope :search, ->(title) {
		where(["lower(title) LIKE (?)","%#{title.downcase}%"])
	}

	def self.last_created_movies(n)
		movie = order(created_at: :desc).limit(n)
		unless movie.present?
			raise
	ActiveRecord::RecordNotFound.new("couldn´t find movie with id=#{id}")
	end
	movie
	end

	paginates_per 12
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :movie
	validates :reviewer, presence: {message: "Error, there isn't any reviewer"}
	validates :content, presence: {message: "Error, there isn't any content"}
end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :artist
	belongs_to :album
	validates :title, uniqueness: {message: "Error, there is a song with this title"}
	validates :title, presence: {message: "Error, there isn´t any title"}
	validates :listeners, presence: {message: "Error, there isn´t any listeners"}
	validates :video_url, presence: {message: "Error, there isn´t any video_url"}
	paginates_per 12
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :artists
	validates :name, presence: {message: "Error, there isn´t any name"}
end

app/models/tag_and_artist.rb
class TagAndArtist < ActiveRecord::Base
end

app/controllers/music_controller.rb
class MusicController < ApplicationController

	def index
		@songs = Song.all.page params[:page]
	end

	def search_song
		@songs = Song.where(["lower(title) LIKE (?)",'%' + params[:title].downcase + '%'])
		@songs.page params[:page]
		if !@songs.empty?
			@songs
		else

			@lastFM_search = LastFM::Track.search(:track => params[:title])

			@lastFM = @lastFM_search['results']['trackmatches']['track']

			if @lastFM != nil
				@songs = @lastFM.inject(Array.new) do |all_songs, track|
					song = Song.find_or_create_by(title: track['name'], listeners: track['listeners'], video_url: track['url'])

					@lastFM_search_artist = LastFM::Artist.get_info(:artist => track['artist'])

					artist = Artist.find_or_create_by(name: track['artist'], info: @lastFM_search_artist['artist']['bio']['summary'])
					if artist != nil
						if song.artist 
						else
							song.artist = artist
						end
					end
					if @lastFM_search_artist['artist']['tags']
						if @lastFM_search_artist['artist']['tags']['tag']
					 		@lastFM_search_artist['artist']['tags']['tag'].each do |tag|
					 			tag_obj = Tag.find_or_create_by name: tag['name']
					 			if artist.tags.find_by name: tag_obj.name
					 			else
					 				artist.tags << tag_obj
					 			end
					 		end
				 		end
				 	end
			 		all_songs << song if song.save
			 		all_songs
		 		end
		 	end
		end
	end

	def search_category
		sql = ""
 		params[:tag].each do |tag|
 		sql += ' OR ' if sql != ""
 			sql += "lower(name) LIKE ('%"+ tag.downcase + "%') "
 		end

		@tags = Tag.where(sql)

		# @busqueda_artistas = LastFM::Tag.get_top_artists(:tag => params[:category] )
		# @printar = @busqueda_artistas['topartists']['artist']
	end

	def random_songs
 		@song = Song.find_by_id(rand(Song.count))
		@page = Nokogiri::HTML(open(@song.video_url))
		@noko = @page.css('div[class="wrapper"]').to_s.html_safe
 	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	class ProjectsController < ApplicationController
	def index
		@projects = Project.last_created_projects(10)
	end

	def show
		@project = Project.find params[:id]
		rescue
			@projects = Project.last_created_projects(10)
	  		render 'error', layout: 'errorlayout'
	end
end
end

app/controllers/song_controller.rb
class SongController < ApplicationController
	def show
		@song = Song.find params[:id]
		
		@page = Nokogiri::HTML(open(@song.video_url))
		@noko = @page.css('div[class="wrapper"]').to_s.html_safe
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/cast_member_helper.rb
module CastMemberHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/music/index.html.erb
<section class="tracks_header">

<h1>Tracks</h1>

<div class="moverboton">
<a href="/music/random_songs" class="rotate_song">
	<span></span>
    <span></span>
    <span>Random<br><br>song!</span>
</a>
</div>

<%= form_tag(search_song_music_index_path, method: :get) do %>
<%= text_field_tag'title', nil, placeholder: 'Search track by title...' %>
<%= submit_tag'Search', class: 'submit_search' %>
<% end %>

<dl class="accordion" data-accordion="">
  <dd class="accordion-navigation">
    <a class='category_display_form' href="#panel1">Search by category &#8616;</a>
    <div id="panel1" class="content">
      <dl class="tabs" data-tab="">
      	<div class="category_form">
			<form accept-charset="UTF-8" action="/music/search_category" method="get"><div style="display:none"><input name="utf8" type="hidden" value="✓"></div>

				<div>
					<%  Tag.all.each do |tag| %>
					    <div class="each_tag"> <%= check_box_tag 'tag[]', tag.name %> <%= tag.name %> </div>
					<% end %>
				</div>

				<div class="submit_category_search">
					<input name="commit" type="submit" value="Search">
				</div>
			</form>
		</div>
	</dl>
	</div>
  </dd>
 </dl>

</section>

<section class='movie_list'>
	<% if @songs == [] %>
		There isn´t any song in the data base
	<% else %>
		<ul><% @songs.each do |song| %>
			<div class='movie_preview'>
				<% if song == nil %>
					There isn´t any song
				<% else %>
					<li>				
						<% if song.artist == nil %>
			
						<% else %>
							<h4><%= link_to(song.title, song_path(song)) %></h4>
							<p>Artist: <%= link_to(song.artist.name, artist_path(song.artist)) %></p>
							<p>Tags: <% song.artist.tags[0..song.artist.tags.length - 2].each do |tag| %>
								<%= tag.name %>, 
							<% end %>
							<% if song.artist.tags.last == nil %>
							<% else %>
								<%= song.artist.tags.last.name %>.
								</p>
								<p>Number of listeners: <%= song.listeners %></p>
							<% end %>
						<% end %>
					</li>
				<% end %>
			</div>
		<% end %></ul>
	<% end %>
</section>

<div class='pagination_section'><p><%= paginate @songs %></p></div>

<script src="assets/jquery.js"></script>
<script src="assets/foundation.js"></script>
<script src="assets/foundation.accordion.js"></script>

<script>
  $(document).foundation({
    accordion: {
      callback : function (accordion) {
        console.log(accordion);
      }
    }
  });
</script>

app/views/music/random_songs.html.erb
<div>
<%if @song.artist == nil %>
	Please,search another song.
<% else %>
	<% if @song.artist.id == nil %>
		Please,search another song.
	<% else %>
		<div class='song_show_items'><h1><%= @song.title %></h1>
		<p>Artist: <%= link_to(@song.artist.name, artist_path(@song.artist)) %></p>
		<br>
		<p>Categories: <% @song.artist.tags[0..@song.artist.tags.length - 2].each do |tag| %>
			<%= link_to(tag.name, tag_path(tag)) %>, 
		<% end %>
		<%= link_to(@song.artist.tags.last.name, tag_path(@song.artist.tags.last)) %>.
		</p>
		<br>
		<p>Number of listeners: <%= @song.listeners %></p>
		<br>
		</div>
		<div id='video_song'><%= @noko %></div>
		</div>
	<% end %>
<% end %>

app/views/music/search_category.html.erb
<div class='song_show_items'>
	<ul>
		<% @tags.each do |tag| %>
			<h1><%= tag.name %></h1>
		<% end %>
		<% @tags.each do |tag| %>
			<% tag.artists.each do |artist| %>
				<li>
					<% if artist.songs == [] %>
					<% else %>
						<%= link_to(artist.name, artist_path(artist)) %>
					<% end %>
				</li><br>
			<%end%>
		<% end %>
	</ul>
</div>

app/views/music/search_song.html.erb
<div class= 'movie_show_items'>
	<% if @songs == [] %>
		Sorry, there isn´t any song with this title.
	<% else %>
		<h1>Songs</h1>
		<% @songs.each do |song| %>
			<%if song.artist == nil %>
				
			<% else %>
				<% if song.artist.id == nil %>
				<% else %>
					<h2 class="song_title"><%= link_to(song.title, song_path(song)) %></h2>
					<p>Artist: <%= link_to(song.artist.name, artist_path(song.artist)) %></p>
					<br>
					<p>Categories: <% song.artist.tags[0..song.artist.tags.length - 2].each do |tag| %>
						<%= link_to(tag.name, tag_path(tag)) %>, 
					<% end %>
					<% if song.artist.tags.length == 0 %>
					<%else%>
						<%= link_to(song.artist.tags.last.name, tag_path(song.artist.tags.last)) %>.
					<% end %>
					</p>
					<br>
					<p>Number of listeners: <%= song.listeners %></p>
					<br>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
</div>