config/routes.rb
Rails.application.routes.draw do
  get '/actor/:full_name' => 'cast_members#show_by_name', as: 'name'
  root 'movies#principal'
  

  resources :movies do
    collection do
      get :random_movies
      get :search
      get :search_category
    end

    member do
      patch :reduce_counter
      patch :increment_counter
    end

    resources :reviews
  end

  resources :movies do
    resources :cast_members
  end

  resources :cast_members do
    resources :movies
  end

  resources :movies do
    resources :categories
  end

  resources :categories do
    resources :movies
  end

  resources :music do
    collection do
      get :random_songs
      get :search_song
      get :search_category
    end
  end

  resources :song do
    resources :artist
  end

  resources :artist do
    resources :songs
  end

  resources :artist do
    resources :tags
  end

  resources :tags do
    resources :artist
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :songs
	belongs_to :artist

	validates :title, uniqueness: {message: "Error, there is an album with this title"}
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :songs
	has_many :albums
	has_and_belongs_to_many :tags

	validates :info, presence: {message: "Error, there isn´t any info"}
	validates :name, presence: {message: "Error, there isn´t any name"}
	validates :name, uniqueness: {message: "Error, there is an artist with this name"}
	paginates_per 20
end

app/models/cast_member.rb
class CastMember < ActiveRecord::Base
	has_and_belongs_to_many :movies
	validates :full_name, presence: {message: "Error, there isn't any name"}
	validates :full_name, uniqueness: {message: "Error, there is an actor with this name"}
	paginates_per 20
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :movies
	validates :name, presence: {message: "Error, there isn´t any name"}
	validates :name, uniqueness: {message: "Error, there is a category with this title"}
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_and_belongs_to_many :cast_members
	has_many :reviews
	has_and_belongs_to_many :categories

	validates :year, presence: {message: "Error, there isn't any year"}
	validates :plot, presence: {message: "Error, there isn't any plot"}
	validates :poster, presence: {message: "Error, there isn't any poster"}
	validates :trailer_url, presence: {message: "Error, there isn't any trailer url"}
	validates :title, uniqueness: {message: "Error, there is a movie with this title"}

	scope :search, ->(title) {
		where(["lower(title) LIKE (?)","%#{title.downcase}%"])
	}

	def self.last_created_movies(n)
		movie = order(created_at: :desc).limit(n)
		unless movie.present?
			raise
	ActiveRecord::RecordNotFound.new("couldn´t find movie with id=#{id}")
	end
	movie
	end

	paginates_per 12
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :movie
	validates :reviewer, presence: {message: "Error, there isn't any reviewer"}
	validates :content, presence: {message: "Error, there isn't any content"}
end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :artist
	belongs_to :album
	validates :title, uniqueness: {message: "Error, there is a song with this title"}
	validates :title, presence: {message: "Error, there isn´t any title"}
	validates :listeners, presence: {message: "Error, there isn´t any listeners"}
	validates :video_url, presence: {message: "Error, there isn´t any video_url"}
	paginates_per 12
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :artists
	validates :name, presence: {message: "Error, there isn´t any name"}
end

app/models/tag_and_artist.rb
class TagAndArtist < ActiveRecord::Base
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	class ProjectsController < ApplicationController
	def index
		@projects = Project.last_created_projects(10)
	end

	def show
		@project = Project.find params[:id]
		rescue
			@projects = Project.last_created_projects(10)
	  		render 'error', layout: 'errorlayout'
	end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/cast_member_helper.rb
module CastMemberHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>What Can I Do</title>
  <link rel="shortcut icon" href="assets/whatcanido.ico" />
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="fixed">
		<nav class="top-bar" data-topbar>
			<ul class="title-area">
	    		<li class="name">
	    			<h1><%= link_to('What Can I Do', root_path) %></h1>
	    		</li>
	<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
	    		<li class="toggle-topbar menu-icon"><a><span>Menu</span></a></li>
			</ul>
			
			<section class="top-bar-section">
	<!-- Left Nav Section -->
		    	<ul class="left">
	    			<li class="divider"></li>
		    		<li class="has-dropdown not-click">
		    			<a>Movies</a>
		        		<ul class="dropdown">
		        			<li class="divider"></li>		        				
        					<li><%= link_to("Movies", movies_path) %></li>
        					<li class="divider"></li>
        					<li><%= link_to("Actors", cast_members_path) %></li>
        					<li class="divider"></li>
        					<li><%= link_to("Categories", categories_path) %></li>        			
		        		</ul>
		    		</li>
		    	</ul>
		    	<ul class="left">
	    			<li class="divider"></li>
		    		<li class="has-dropdown not-click">
		    			<a>Music</a>
		        		<ul class="dropdown">
		        			<li class="divider"></li>		        				
        					<li><%= link_to("Tracks", music_index_path) %></li>
        					<li class="divider"></li>
        					<li><%= link_to("Artists", artist_index_path) %></li>
        					<li class="divider"></li>
        					<li><%= link_to("Tags", tags_path) %></li>        			
		        		</ul>
		    		</li>
		    	</ul>
		    </div>


	<!-- Right Nav Section -->
		    	<ul class="right">
		    		
		    	</ul>
			</section>
		</nav>

	<article>
		<%= yield %>
	</article>
	<footer class='text-center'>
		<p class="footer_text">Ironhack Project | What Can I Do & Co.</p>
	</footer>
	<script>$(document).foundation();</script>
</body>
</html>